name: Fetch and Commit Latest Releases

on:  # 触发器设置
  schedule:  # 定时任务
    - cron: '0 0 * * 0'  # 每周日午夜执行 (Cron 表达式)
  workflow_dispatch:  # 允许手动触发此工作流

jobs:  # 定义作业
  fetch-releases:  # 作业名称
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本运行此作业
    steps:  # 步骤列表
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }} # 使用 PAT

      - name: Fetch latest release assets
        run: |
          # 安装必要的工具
          sudo apt-get update && sudo apt-get install -y curl jq git
      
          # 获取最新的 release 信息
          LATEST_RELEASE_INFO=$(curl --silent "https://api.github.com/repos/chen08209/FlClash/releases/latest")
      
          # 提取 assets 列表
          ASSETS=$(echo $LATEST_RELEASE_INFO | jq -r '.assets[] | .browser_download_url')
      
          # 进入工作区目录下载文件
          cd ${GITHUB_WORKSPACE}
      
          # 遍历 assets 并下载匹配的文件
          for asset in $ASSETS; do
            if [[ $asset == *"arm64-v8a"* ]] || [[ $asset == *"armeabi-v7a"* ]] || [[ $asset == *"x86_64"* ]] || [[ $asset == *"amd64-setup"* ]]; then
              FILENAME=$(basename "$asset")
              echo "Downloading $FILENAME..."
              curl -L -o "$FILENAME" "$asset"
            fi
          done

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automatically committed changes by GitHub Actions'
