name: Fetch and Commit Latest Releases

on:  # 触发器设置
  schedule:  # 定时任务
    - cron: '0 0 * * 0'  # 每周日午夜执行 (Cron 表达式)
  workflow_dispatch:  # 允许手动触发此工作流

jobs:  # 定义作业
  fetch-releases:  # 作业名称
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本运行此作业
    steps:  # 步骤列表
      - name: Checkout code  # 检出代码
        uses: actions/checkout@v3  # 使用 checkout action v3 版本
        with:  # 设置参数
          fetch-depth: 0  # 检出整个仓库的历史记录，以便于后续提交更改

      - name: Fetch latest release assets  # 获取最新发布的资源文件
        run: |  # 执行 shell 命令
          # 安装必要的工具
          sudo apt-get update && sudo apt-get install -y curl jq

          # 获取最新的 release 信息
          LATEST_RELEASE_INFO=$(curl --silent "https://api.github.com/repos/chen08209/FlClash/releases/latest")
          LATEST_TAG_NAME=$(echo $LATEST_RELEASE_INFO | jq -r '.tag_name')

          # 构造每个文件的 URL
          APK_ARM64_URL="https://github.com/chen08209/FlClash/releases/download/$LATEST_TAG_NAME/FlClash-$LATEST_TAG_NAME-android-arm64-v8a.apk"
          APK_ARMEABI_URL="https://github.com/chen08209/FlClash/releases/download/$LATEST_TAG_NAME/FlClash-$LATEST_TAG_NAME-android-armeabi-v7a.apk"
          APK_X86_64_URL="https://github.com/chen08209/FlClash/releases/download/$LATEST_TAG_NAME/FlClash-$LATEST_TAG_NAME-android-x86_64.apk"
          EXE_AMD64_URL="https://github.com/chen08209/FlClash/releases/download/$LATEST_TAG_NAME/FlClash-$LATEST_TAG_NAME-windows-amd64-setup.exe"

          # 进入工作区目录下载文件
          cd ${GITHUB_WORKSPACE}
          curl -L -o FlClash-$LATEST_TAG_NAME-android-arm64-v8a.apk "$APK_ARM64_URL"
          curl -L -o FlClash-$LATEST_TAG_NAME-android-armeabi-v7a.apk "$APK_ARMEABI_URL"
          curl -L -o FlClash-$LATEST_TAG_NAME-android-x86_64.apk "$APK_X86_64_URL"
          curl -L -o FlClash-$LATEST_TAG_NAME-windows-amd64-setup.exe "$EXE_AMD64_URL"

      - name: 提交更新  # 提交更新后的文件
        uses: actions-x/commit@v6  # 使用 actions-x/commit action v6 版本
        with:  # 设置参数
          commit_message: "更新"  # 提交消息
